location = /xapp/ {
    # initial request - proxy it with gateway to check authorization
    # remove it and use only location /xapp when using separate guacamole (as gateway don't know where separate guacamole is)
    # trailing slash is important for guacamole (or it will return redirect)
    proxy_pass http://hypha-gateway:8091/guacamole/;
    proxy_buffering off;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_set_header Host $host;
    access_log off;
    # allow large uploads (default=1m)
    # 4096m = 4GByte
    client_max_body_size 4096m;
}

location = /xapp/api/tokens {
    # authorization request - proxy it with gateway to check authorization
    # remove it and use only location /xapp when using separate guacamole (as gateway don't know where separate gateway is)
    # trailing slash is important for guacamole (or it will return redirect)
    proxy_pass http://hypha-gateway:8091/guacamole/api/tokens;
    proxy_buffering off;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_set_header Host $host;
    access_log off;
    # allow large uploads (default=1m)
    # 4096m = 4GByte
    client_max_body_size 4096m;
}

location = /xapp {
    # overwrite guacamole redirect that lead to /guacamole/ instead or /xapp/
    return 301 /xapp/$is_args$args;
}

location /xapp {
    # nested requests - pass it right through to not make client some way add auth token to each guacamole request
    # set public guacamole address here when using separate guacamole
    proxy_pass http://hypha-guacamole-client:8080/guacamole;
    proxy_buffering off;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_set_header Host $host;
    access_log off;
    # allow large uploads (default=1m)
    # 4096m = 4GByte
    client_max_body_size 4096m;
}
